
name: .NET

on:
  push:
    branches: 
    - master
    - develop
  pull_request:
    branches: 
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore BioPulse-Rpi/BioPulse-Rpi.sln
      working-directory: ../BioPulse-Rpi
      
    - name: Build
      run: dotnet build BioPulse-Rpi/BioPulse-Rpi.sln
      working-directory: ../BioPulse-Rpi

